name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: ใช้ Action สำเร็จรูปในการดึงโค้ดจาก Repo ลงมาในเครื่องจำลอง
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: ติดตั้ง Node.js ในเครื่องจำลอง
      - name: Setup Node.js
        uses: actions/setup-node@v4 # หรือ actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm' # ช่วยให้ติดตั้งแพ็กเกจรอบถัดๆ ไปไวขึ้น

      # Step 3: ติดตั้ง Dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: ลองสั่ง Build โค้ดดูว่ามี Error ไหม
      - name: Build project
        run: npm run build